# Memorix Development Configuration

spring:
  application:
    name: memorix
    
  datasource:
    url: jdbc:postgresql://localhost:5432/memorix_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
logging:
  level:
    io.memorix: DEBUG
    org.springframework: INFO
    
memorix:
  embedding:
    provider: openai  # Use real OpenAI in dev
  token-counter: approximate

