name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    
    env:
      SPRING_PROFILES_ACTIVE: test
      MEMORIX_EMBEDDING_PROVIDER: mock
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Run tests (skip Testcontainer tests)
      run: mvn clean test -Dtest='!ImportancePersistenceTest,!SearchFunctionalityIntegrationTest,!**/ValidationErrorHandlingTest'
      
    - name: Generate coverage report
      run: mvn jacoco:report
      
    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v4
      if: success()
      continue-on-error: true
      with:
        files: ./memorix-core/target/site/jacoco/jacoco.xml
        
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: memorix-jar
        path: memorix-core/target/*.jar
        retention-days: 7
        
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t memorix:test .
      
    - name: Test Docker image
      run: |
        docker images | grep memorix
        echo "✅ Docker image built successfully"

